// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/whoami.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var whoami_default = defineTool({
  name: "whoami",
  title: "Who am I",
  description: "Return the signed-in user's identity, role, and organization within SIA.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { createClient } = await import("npm:@supabase/supabase-js@^2.103.0");
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data: profile, error } = await supabase.from("profiles").select("id, full_name, email, role, organization_id, organizations(name, industry, country)").eq("id", ctx.getUserId()).single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(profile, null, 2) }],
      structuredContent: { profile }
    };
  }
});

// src/lib/mcp/tools/list-org-units.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_org_units_default = defineTool2({
  name: "list_org_units",
  title: "List organizational units",
  description: "List all organizational units (departments, teams, etc.) in the signed-in user's organization, with hierarchy path and type.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { createClient } = await import("npm:@supabase/supabase-js@^2.103.0");
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("org_units").select("id, name, parent_id, depth, is_active, unit_type_id, org_unit_types(name, level)").order("depth", { ascending: true }).order("name", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { units: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-unit-types.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var list_unit_types_default = defineTool3({
  name: "list_unit_types",
  title: "List hierarchy levels",
  description: "List the organization's hierarchy level definitions (e.g. Division, Department, Team) in order.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { createClient } = await import("npm:@supabase/supabase-js@^2.103.0");
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    const { data, error } = await supabase.from("org_unit_types").select("id, name, level").order("level", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { levels: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-employees.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var list_employees_default = defineTool4({
  name: "list_employees",
  title: "List employees",
  description: "List employees (profiles) in the signed-in user's organization. Optionally filter by role (hr_admin, manager, employee).",
  inputSchema: {
    role: z.enum(["hr_admin", "manager", "employee"]).optional().describe("Optional role filter.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ role }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const { createClient } = await import("npm:@supabase/supabase-js@^2.103.0");
    const supabase = createClient(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY,
      {
        global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
        auth: { persistSession: false, autoRefreshToken: false }
      }
    );
    let query = supabase.from("profiles").select("id, full_name, email, role, created_at").order("full_name", { ascending: true });
    if (role) query = query.eq("role", role);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { employees: data ?? [] }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "jntmckvvulntmywwzmen";
var mcp_default = defineMcp({
  name: "sia-mcp",
  title: "SIA \u2014 Smart Performance Management",
  version: "0.1.0",
  instructions: "Tools for SIA, a multi-tenant HR performance management platform. Use `whoami` to see the signed-in user, `list_unit_types` to see hierarchy levels, `list_org_units` to explore the org structure, and `list_employees` to find people in the organization. All reads are scoped to the signed-in user's organization.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [whoami_default, list_org_units_default, list_unit_types_default, list_employees_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
